name: tmr3
channels:
- conda-forge
dependencies:
- python=3.7
- ipython
- numpy
- pandas
- pyqt
- pip
- pip:
  - psychopy
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client
  - pyobjc==7.3; platform_system != "Windows"