name: twc

dependencies:
  - python=3.7.1
  - ipython=7.27.0
  - pyserial=3.5
  - numpy=1.21.2
  - pandas=1.3.3
  - pyqtgraph=0.11.0
  - pyqt=5.6.0
  # - pyaudio=0.2.11
  # - conda-forge::python-sounddevice=0.4.1
  # - conda-forge::pysoundfile=0.10.3
  - pip=21.2.4
  # - pip:
  #   - pyttsx3=2.90 # text2speech
  #   # - yasa
